name: Build and Deploy via DockerHub

on:
    push: 
        branches: ['main']
    pull_request: 
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Build Docker Image
              run: | 
                docker build -t jbtest:latest .

